name: Scrape Youtube Trends Data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 18 * * *' # Every hour. Ref https://crontab.guru/examples.html




jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: get youtube data
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        pip3 install install pandas google-api-python-client pytz
        python3 scrape.py
    - uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub sets this for you
